[build-system]
requires = ["setuptools==59.6.0", "wheel==0.37.1"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
