# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Reusable - Build the package

on:
  workflow_call:
    inputs:
      build_variant:
        type: string
        default: true
      py:
        type: string
        required: true
      torch:
        type: string
        required: true
      sanitizers:
        type: string
        default: true
      dev_stamp:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  build_package:
    name: Build the package
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux:1-${{ inputs.build_variant }}
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv /venv-build

          echo /venv-build/bin >> $GITHUB_PATH
      - name: Install PyTorch
        run: |
          pip install torch==${{ inputs.torch }}\
            --extra-index-url https://download.pytorch.org/whl/${{ inputs.build_variant }}
      - name: Stamp the version with the current date
        if: inputs.dev_stamp
        run: |
          version=$(cat VERSION)

          tools/set-version ${version%.dev0}.dev$(date +%Y%m%d)
      - name: Build the C++ library and the extension modules
        run: |
          sanitizers=${{ inputs.sanitizers }}

          # Since they do not play well together, we perform LTO only if no
          # sanitizer is used.
          if [[ $sanitizers == nosan ]]; then
            lto=ON
          else
            lto=OFF
          fi

          cmake -GNinja\
                -DCMAKE_BUILD_TYPE=Release\
                -DFAIRSEQ2_TREAT_WARNINGS_AS_ERRORS=ON\
                -DFAIRSEQ2_PERFORM_LTO=$lto\
                -DFAIRSEQ2_DEVELOP_PYTHON=OFF\
                -DFAIRSEQ2_SANITIZERS="${sanitizers/_/;}"\
                -B build

          cmake --build build
      - name: Build the wheel
        run: |
          # We follow PEP 600 and use the new `manylinux_2_17_x86_64` platform
          # tag which means we support glibc >= 2.17 on x86.
          pip wheel .\
            --build-option --plat-name --build-option manylinux_2_17_x86_64\
            --no-deps\
            --wheel-dir /wheelhouse
      - name: Upload the build artifacts to staging
        uses: actions/upload-artifact@v3
        with:
          name: wheel-py${{ inputs.py }}-pt${{ inputs.torch }}-${{ inputs.build_variant }}-${{ inputs.sanitizers }}
          path: /wheelhouse
          retention-days: 3
