# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Build the documentation

on:
  workflow_call:
    inputs:
      py:
        type: string
        required: true
      torch:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_x86_64:1-cpu
    steps:
      - name: Download the wheel from staging
        uses: actions/download-artifact@v3
        with:
          name: wheel-linux_x86_64-py${{ inputs.py }}-pt${{ inputs.torch }}-cpu-nosan
          path: ~/wheelhouse/
      - name: Check-out the repository
        uses: actions/checkout@v3
      - name: Set up the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv ~/venv

          echo ~/venv/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==${{ inputs.torch }}\
            --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Install the requirements
        run: |
          pip install --requirement doc/requirements.txt
      - name: Install the wheel
        run: |
          pip install ~/wheelhouse/*.whl --no-cache-dir
      - name: Run Sphinx
        run: |
          make CONDA_PREFIX=~/venv doc
      - name: Upload the documentation to staging
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: doc/build/html/
          retention-days: 3
