# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Build and test wheel (Linux)

on:
  workflow_call:
    inputs:
      torch:
        type: string
        required: true
      py:
        type: string
        required: true
      arch:
        type: string
        required: true
      variant:
        type: string
        required: true
      sanitizers:
        type: string
        default: 'nosan'
      dev_stamp:
        type: boolean
        default: false
      run_integration_tests:
        type: boolean
        default: false
      run_on_device:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_${{ inputs.arch }}:1-${{ inputs.variant }}
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install libsndfile
        run: |
          yum --assumeyes install libsndfile-devel
      - name: Set up the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv ~/venv

          echo ~/venv/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==${{ inputs.torch }}\
            --extra-index-url https://download.pytorch.org/whl/${{ inputs.variant }}
      - name: Install the requirements
        run: |
          pip install --requirement requirements-build.txt
      - name: Stamp the version with the current date
        if: inputs.dev_stamp
        run: |
          version=$(cat VERSION)

          tools/set-version.sh ${version%.dev0}.dev$(date +%Y%m%d)
      - name: Build the C++ library and the extension module
        env:
          VARIANT: ${{ inputs.variant }}
          SANITIZERS: ${{ inputs.sanitizers }}
        run: |
          # We build our CUDA kernels for Volta and Ampere.
          if [[ $VARIANT == cu* ]]; then
            cuda_archs="70-real;80-real;80-virtual"

            cuda=ON
          else
            cuda=OFF
          fi

          # Since they do not play well together, we perform LTO only if no
          # sanitizer is enabled.
          if [[ $SANITIZERS == nosan ]]; then
            build_type=Release

            lto=ON
          else
            build_type=Debug

            lto=OFF
          fi

          cmake -GNinja\
                -DCMAKE_BUILD_TYPE=$build_type\
                -DCMAKE_CUDA_ARCHITECTURES=$cuda_archs\
                -DFAIRSEQ2_PYTHON_DEVEL=OFF\
                -DFAIRSEQ2_PERFORM_LTO=$lto\
                -DFAIRSEQ2_SANITIZERS="${SANITIZERS/_/;}"\
                -DFAIRSEQ2_TREAT_WARNINGS_AS_ERRORS=ON\
                -DFAIRSEQ2_USE_CUDA=$cuda\
                -B build

          cmake --build build
      - name: Create the wheel
        run: |
          # We follow PEP 600 and use the new `manylinux_2_17_x86_64` platform
          # tag which means we support glibc >= 2.17.
          pip wheel .\
                    --no-deps\
                    --build-option --plat-name\
                    --build-option manylinux_2_17_${{ inputs.arch }}\
                    --wheel-dir build/wheelhouse
      - name: Upload the wheel and the native tests to staging
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-pt${{ inputs.torch }}-py${{ inputs.py }}-linux_${{ inputs.arch }}-${{ inputs.variant }}-${{ inputs.sanitizers }}
          path: |
            build/wheelhouse/*.whl
            build/tests/native/run-tests
          retention-days: 1

  test:
    name: Test
    needs: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_${{ inputs.arch }}:1-${{ inputs.variant }}
    steps:
      - name: Install libsndfile
        run: |
          yum --assumeyes install libsndfile-devel
      - name: Download the wheel and the native tests from staging
        uses: actions/download-artifact@v3
        with:
          name: artifacts-pt${{ inputs.torch }}-py${{ inputs.py }}-linux_${{ inputs.arch }}-${{ inputs.variant }}-${{ inputs.sanitizers }}
          path: ~/build-artifacts/
      - name: Check-out the repository
        uses: actions/checkout@v3
      - name: Set up the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv ~/venv

          echo ~/venv/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==${{ inputs.torch }}\
            --extra-index-url https://download.pytorch.org/whl/${{ inputs.variant }}
      - name: Install the requirements
        run: |
          pip install --requirement requirements-devel.txt
      - name: Install the wheel
        run: |
          for whl in ~/build-artifacts/wheelhouse/*.whl; do
            pip install $whl --no-cache-dir
          done
      - name: Set the sanitizer variables
        if: inputs.sanitizers != 'nosan'
        env:
          SANITIZERS: ${{ inputs.sanitizers }}
        run: |
          {
            # We can't enable container overflow checks due to false positives
            # in non-instrumented dependencies.
            echo ASAN_OPTIONS=detect_container_overflow=0

            echo LSAN_OPTIONS=suppressions=LSan.supp,exitcode=0,log_path=$HOME/lsan.out

            for sanitizer in ${SANITIZERS//_/ }; do
              # LIBASAN and LIBTSAN environment variables are defined in the
              # container image.
              if [[ $sanitizer == asan ]]; then
                echo SANITIZER_LIB=$(echo $LIBASAN)

                break
              fi

              if [[ $sanitizer == tsan ]]; then
                echo SANITIZER_LIB=$(echo $LIBTSAN)

                break
              fi
            done
          } >> $GITHUB_ENV
      - name: Run the native tests
        run: |
          chmod 755 ~/build-artifacts/tests/native/run-tests

          LD_LIBRARY_PATH=~/venv/lib/python${{ inputs.py }}/site-packages/fairseq2/lib\
            ~/build-artifacts/tests/native/run-tests
      - name: Run the Python tests
        env:
          RUN_INTEGRATION_TESTS: ${{ inputs.run_integration_tests }}
          RUN_ON_DEVICE: ${{ inputs.run_on_device }}
        run: |
          if [[ $RUN_INTEGRATION_TESTS == true ]]; then
            integration=--integration
          fi

          if [[ $RUN_ON_DEVICE != true ]]; then
            dev=cpu
          else
            dev=cuda:0
          fi

          LD_PRELOAD=${SANITIZER_LIB} pytest -rP --device $dev $integration --verbose
      - name: Check the output of the leak sanitizer
        if: env.LSAN_OPTIONS != ''
        run: |
          # Unfortunately Python leaks quite a bit of memory, so we cannot rely
          # on the raw output of LSan. As a rudimentary workaround, we check if
          # any stack frame has a symbol containing the word 'fairseq2'.
          for f in ~/lsan.out.*; do
            if cat $f | tee /dev/stderr | grep --quiet 'fairseq2'; then
              exit 1
            fi
          done
