# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Build documentation

on:
  pull_request:
    paths:
      - '**.py'
      - '**.pyi'
      - 'doc/**'
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  generate:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_x86_64:1-cpu
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
      - name: Install libsndfile
        run: |
          yum --assumeyes install libsndfile-devel
      - name: Set up the Python virtual environment
        run: |
          python3.10 -m venv ~/venv

          echo ~/venv/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==2.0.1\
            --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Install the requirements
        run: |
          pip install --requirement requirements-build.txt --requirement doc/requirements.txt
      - name: Install the package
        run: |
          pip install --editable .
      - name: Run Sphinx
        working-directory: doc
        run: |
          make html SPHINXOPTS="-W"
      - name: Copy the version file into the documentation
        run: |
          cp VERSION doc/build/html
      - name: Upload the documentation to staging
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: doc/build/html/
          retention-days: 1
