# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: CI (Linux)

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'ci/**'

jobs:
  build_wheel-x86_64:
    name: Build wheel (pt${{matrix.torch}}, py${{ matrix.py}}, linux_x86_64, ${{ matrix.variant }}, ${{ matrix.sanitizers }})
    uses: ./.github/workflows/build_wheel-linux.yaml
    strategy:
      matrix:
        include:
          # PT 1.12.1
          - torch: '1.12.1'  # CPU
            py: '3.8'
            variant: 'cpu'
            sanitizers: 'nosan'

          # PT 2.0.1
          - torch: '2.0.1'   # CPU
            py: '3.8'
            variant: 'cpu'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cpu'
            sanitizers: 'nosan'

          - torch: '2.0.1'   # CUDA 11.7
            py: '3.8'
            variant: 'cu117'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cu117'
            sanitizers: 'nosan'

          - torch: '2.0.1'   # CUDA 11.8
            py: '3.8'
            variant: 'cu118'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cu118'
            sanitizers: 'nosan'

          - torch: '2.0.1'   # ASAN_UBSAN
            py: '3.10'
            variant: 'cpu'
            sanitizers: 'asan_ubsan'
    with:
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      arch: 'x86_64'
      variant: ${{ matrix.variant }}
      sanitizers: ${{ matrix.sanitizers }}
