# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Lint Python

on:
  pull_request:
    paths:
      - '**.py'
      - '**.pyi'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint (py${{ matrix.py }})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_x86_64:1-cpu
    strategy:
      # Ensure that we get the results of all linters even if some of them fail.
      fail-fast: false
      matrix:
        py: ['3.8', '3.10']
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
      - name: Set up the Python virtual environment
        run: |
          python${{ matrix.py }} -m venv ~/venv-lint

          echo ~/venv-lint/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==1.12.1\
            --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Install the requirements
        run: |
          pip install --requirement requirements-devel.txt
      - name: Install the package
        id: setup
        run: |
          pip install --editable .
      - name: Run isort
        if: success() || (failure() && steps.setup.outcome == 'success')
        run: |
          isort --check .
      - name: Run black
        if: success() || (failure() && steps.setup.outcome == 'success')
        run: |
          black --check .
      - name: Run flake8
        if: success() || (failure() && steps.setup.outcome == 'success')
        run: |
          flake8 .
      - name: Run mypy
        if: success() || (failure() && steps.setup.outcome == 'success')
        run: |
          mypy --pretty .
