# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Lint C++

on:
  pull_request:
    paths:
      - '**.h'
      - '**.cc'
      - '**.cu'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_x86_64:1-cu116-clang
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up the Python virtual environment
        run: |
          python3.8 -m venv ~/venv-lint

          echo ~/venv-lint/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==1.12.1\
            --extra-index-url https://download.pytorch.org/whl/cu116
      - name: Install the requirements
        run: |
          pip install --requirement requirements-build.txt
      - name: Build the compilation database
        id: setup
        run: |
          # CUDA 11.6 does not support clang 15. Since we are only building the
          # compilation database, this is safe though.
          export CUDAFLAGS="--allow-unsupported-compiler"

          CC=clang CXX=clang++ cmake -GNinja -DCMAKE_BUILD_TYPE=Release -B build
#      - name: Run clang-format
#        if: success() || (failure() && steps.setup.outcome == 'success')
#        run: |
#          tools/linters/run-clang-format --dry-run .
      - name: Run clang-tidy
        if: success() || (failure() && steps.setup.outcome == 'success')
        run: |
          run-clang-tidy -p build -config="{InheritParentConfig: true, WarningsAsErrors: '*'}" -quiet
