# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Lint C++

on:
  workflow_call:
    inputs:
      py:
        type: string
        required: true
      torch:
        type: string
        required: true
      variant:
        type: string
        default: 'cpu'

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Lint C++
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_x86_64:1-${{ inputs.variant }}-clang
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv /venv-lint

          echo /venv-lint/bin >> "$GITHUB_PATH"
      - name: Install the requirements
        run: |
          pip install --upgrade pip
      - name: Install PyTorch
        run: |
          pip install torch==${{ inputs.torch }}\
            --extra-index-url https://download.pytorch.org/whl/${{ inputs.variant }}
      - name: Build the compilation database
        id: lint_start
        run: |
          CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release -B build
      - name: Run clang-format
        if: success() || (failure() && steps.lint_start.outcome == 'success')
        run: |
          tools/porcelain/run-clang-format --dry-run
      - name: Run clang-tidy
        if: success() || (failure() && steps.lint_start.outcome == 'success')
        run: |
          run-clang-tidy -p build -quiet
