# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Build a wheel (Linux)

on:
  workflow_call:
    inputs:
      py:
        type: string
        required: true
      torch:
        type: string
        required: true
      arch:
        type: string
        default: 'x86_64'
      variant:
        type: string
        default: 'cpu'
      sanitizers:
        type: string
        default: 'nosan'
      dev_stamp:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_${{ inputs.arch }}:1-${{ inputs.variant }}
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv ~/venv-build

          echo ~/venv-build/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==${{ inputs.torch }}\
            --extra-index-url https://download.pytorch.org/whl/${{ inputs.variant }}
      - name: Install the requirements
        run: |
          pip install --requirement requirements-build.txt
      - name: Stamp the version with the current date
        if: inputs.dev_stamp
        run: |
          version=$(cat VERSION)

          tools/set-version ${version%.dev0}.dev$(date +%Y%m%d)
      - name: Build the C++ library and the extension modules
        run: |
          variant=${{ inputs.variant }}

          # We build our CUDA kernels for Volta and Ampere.
          if [[ $variant == cu* ]]; then
            cuda_archs="70-real;80-real;80-virtual"
          fi

          sanitizers=${{ inputs.sanitizers }}

          # Since they do not play well together, we perform LTO only if no
          # sanitizer is used.
          if [[ $sanitizers == nosan ]]; then
            lto=ON
          else
            lto=OFF
          fi

          cmake -GNinja\
                -DCMAKE_BUILD_TYPE=Release\
                -DCMAKE_CUDA_ARCHITECTURES=$cuda_archs\
                -DFAIRSEQ2_TREAT_WARNINGS_AS_ERRORS=ON\
                -DFAIRSEQ2_PERFORM_LTO=$lto\
                -DFAIRSEQ2_EDITABLE_PYTHON=OFF\
                -DFAIRSEQ2_SANITIZERS="${sanitizers/_/;}"\
                -B build

          cmake --build build
      - name: Create the wheel
        run: |
          # We follow PEP 600 and use the new `manylinux_2_17_x86_64` platform
          # tag which means we support glibc >= 2.17.
          pip wheel .\
                    --no-deps\
                    --build-option --plat-name\
                    --build-option manylinux_2_17_${{ inputs.arch }}\
                    --wheel-dir ~/wheelhouse
      - name: Upload the wheel to staging
        uses: actions/upload-artifact@v3
        with:
          name: wheel-linux_${{ inputs.arch }}-py${{ inputs.py }}-pt${{ inputs.torch }}-${{ inputs.variant }}-${{ inputs.sanitizers }}
          path: ~/wheelhouse
          retention-days: 3
