# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Run the tests (Linux)

on:
  workflow_call:
    inputs:
      py:
        type: string
        required: true
      torch:
        type: string
        required: true
      arch:
        type: string
        default: 'x86_64'
      variant:
        type: string
        default: 'cpu'
      sanitizers:
        type: string
        default: 'nosan'
      run_integration:
        type: boolean
        default: false
      run_on_cuda:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fairinternal/fairseq2-ci-manylinux_${{ inputs.arch }}:1-${{ inputs.variant }}
    steps:
      - name: Download the wheel from staging
        uses: actions/download-artifact@v3
        with:
          name: wheel-linux_${{ inputs.arch }}-py${{ inputs.py }}-pt${{ inputs.torch }}-${{ inputs.variant }}-${{ inputs.sanitizers }}
          path: ~/wheelhouse/
      - name: Download the native tests from staging
        uses: actions/download-artifact@v3
        with:
          name: tests-linux_${{ inputs.arch }}-py${{ inputs.py }}-pt${{ inputs.torch }}-${{ inputs.variant }}-${{ inputs.sanitizers }}
          path: ~/tests/
      - name: Check-out the repository
        uses: actions/checkout@v3
      - name: Set up the Python virtual environment
        run: |
          python${{ inputs.py }} -m venv ~/venv

          echo ~/venv/bin >> "$GITHUB_PATH"
      - name: Install PyTorch
        run: |
          pip install torch==${{ inputs.torch }}\
            --extra-index-url https://download.pytorch.org/whl/${{ inputs.variant }}
      - name: Install the requirements
        run: |
          pip install --requirement requirements-devel.txt
      - name: Install the wheel
        run: |
          pip install ~/wheelhouse/*.whl --no-cache-dir
      - name: Set the sanitizer variables
        if: inputs.sanitizers != 'nosan'
        env:
          SANITIZERS: ${{ inputs.sanitizers }}
        run: |
          {
            echo ASAN_OPTIONS=suppressions=ASan.supp

            echo LSAN_OPTIONS=suppressions=LSan.supp,exitcode=0,log_path=$HOME/lsan.out

            for sanitizer in ${SANITIZERS//_/ }; do
              # LIBASAN and LIBTSAN environment variables are defined in the
              # container image.
              if [[ $sanitizer == asan ]]; then
                echo SANITIZER_LIB=$(echo $LIBASAN)

                break
              fi

              if [[ $sanitizer == tsan ]]; then
                echo SANITIZER_LIB=$(echo $LIBTSAN)

                break
              fi
            done
          } >> $GITHUB_ENV
      - name: Run the native tests
        run: |
          chmod 755 ~/tests/run-tests

          LD_LIBRARY_PATH=~/venv/lib/python${{ inputs.py }}/site-packages/fairseq2/lib\
            ~/tests/run-tests
      - name: Run the Python tests
        env:
          RUN_INTEGRATION: ${{ inputs.run_integration }}
          RUN_ON_CUDA: ${{ inputs.run_on_cuda }}
        run: |
          if [[ $RUN_INTEGRATION == true ]]; then
            integration=--integration
          fi

          if [[ $RUN_ON_CUDA != true ]]; then
            dev=cpu
          else
            dev=cuda:0
          fi

          LD_PRELOAD=${SANITIZER_LIB} pytest -rP --device $dev $integration --verbose
      - name: Check the output of the leak sanitizer
        if: env.LSAN_OPTIONS != ''
        run: |
          result=0

          # Unfortunately Python leaks quite a bit of memory, so we cannot rely
          # on the raw output of LSan. As a rudimentary workaround, we check if
          # any stack frame has a symbol containing the word 'fairseq2'.
          for f in ~/lsan.out.*; do
            if cat $f | tee /dev/stderr | grep --quiet 'fairseq2'; then
              result=1
            fi
          done

          exit $result
