# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: On nightly schedule

on:
  # At 1:15AM UTC on every Monday, Wednesday, and Friday.
  schedule:
    - cron: '15 1 * * 1,3,5'

jobs:
  build_and_test:
    name: Build and test the project
    uses: ./.github/workflows/build_and_test_project.yaml
    with:
      dev_stamp: true
      run_all_cuda_tests: true

  publish:
    name: Publish the artifacts
    needs: build_and_test
    uses: ./.github/workflows/publish_artifacts.yaml
    with:
      release_type: nightly
