# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Perform release

run-name: Perform release (${{ inputs.release_type }})

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        options:
          - 'nightly'
          - 'rc'
          - 'stable'

jobs:
  build_and_test:
    name: Build and test the project
    uses: ./.github/workflows/build_and_test_project.yaml
    with:
      dev_stamp: ${{ inputs.release_type == 'nightly' }}
      run_all_cuda_tests: true

  publish:
    name: Publish the artifacts
    needs: build_and_test
    uses: ./.github/workflows/publish_artifacts.yaml
    with:
      release_type: ${{ inputs.release_type }}
