# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Publish wheel

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      torch:
        type: string
        required: true
      py:
        type: string
        required: true
      arch:
        type: string
        required: true
      variant:
        type: string
        required: true
      release_type:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Download the wheel from staging
        uses: actions/download-artifact@v3
        with:
          name: artifacts-pt${{ inputs.torch }}-py${{ inputs.py }}-${{ inputs.os }}_${{ inputs.arch }}-${{ inputs.variant }}-nosan
          path: ~/build-artifacts/
      - name: Upload the wheel to S3
        env:
          TORCH: ${{ inputs.torch }}
          VARIANT: ${{ inputs.variant }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_id }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_access_key }}
#          AWS_DEFAULT_REGION: us-east-1
        run: |
          for pkg in ~/build-artifacts/wheelhouse/*.whl; do
              echo aws s3 cp "$pkg" "s3://dl.fbaipublicfiles.com/fairseq2/${{ inputs.release_type }}/pt${TORCH/./}/$VARIANT/" --acl public-read
          done
