# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

name: Release

run-name: Relase (${{ inputs.release_type || 'nightly' }})

on:
  # At 1:15AM UTC on every Monday.
  schedule:
    - cron: '15 1 * * 1'
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        required: true
        options:
          - 'nightly'
          - 'rc'
          - 'stable'

jobs:
  lint_cc:
    name: Lint C++
    uses: ./.github/workflows/lint_cc.yaml

  lint_py:
    name: Lint Python
    uses: ./.github/workflows/lint_py.yaml

  lint_sh:
    name: Lint shell scripts
    uses: ./.github/workflows/lint_sh.yaml

  build_doc:
    name: Build documentation
    uses: ./.github/workflows/build_doc.yaml

  build_wheel-linux-x86_64:
    name: Build wheel (pt${{matrix.torch}}, py${{ matrix.py}}, linux_x86_64, ${{ matrix.variant }}, ${{ matrix.sanitizers }})
    needs: [lint_cc, lint_py, lint_sh]
    uses: ./.github/workflows/build_wheel-linux.yaml
    strategy:
      matrix:
        include:
          # PT 1.12.1
          - torch: '1.12.1'  # CPU
            py: '3.8'
            variant: 'cpu'
            sanitizers: 'nosan'
          - torch: '1.12.1'
            py: '3.9'
            variant: 'cpu'
            sanitizers: 'nosan'
          - torch: '1.12.1'
            py: '3.10'
            variant: 'cpu'
            sanitizers: 'nosan'

          - torch: '1.12.1'  # CUDA 11.6
            py: '3.8'
            variant: 'cu116'
            sanitizers: 'nosan'
          - torch: '1.12.1'
            py: '3.9'
            variant: 'cu116'
            sanitizers: 'nosan'
          - torch: '1.12.1'
            py: '3.10'
            variant: 'cu116'
            sanitizers: 'nosan'

          # PT 1.13.1
          - torch: '1.13.1'  # CPU
            py: '3.8'
            variant: 'cpu'
            sanitizers: 'nosan'
          - torch: '1.13.1'
            py: '3.9'
            variant: 'cpu'
            sanitizers: 'nosan'
          - torch: '1.13.1'
            py: '3.10'
            variant: 'cpu'
            sanitizers: 'nosan'

          - torch: '1.13.1'  # CUDA 11.6
            py: '3.8'
            variant: 'cu116'
            sanitizers: 'nosan'
          - torch: '1.13.1'
            py: '3.9'
            variant: 'cu116'
            sanitizers: 'nosan'
          - torch: '1.13.1'
            py: '3.10'
            variant: 'cu116'
            sanitizers: 'nosan'

          # PT 2.0.1
          - torch: '2.0.1'   # CPU
            py: '3.8'
            variant: 'cpu'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.9'
            variant: 'cpu'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cpu'
            sanitizers: 'nosan'

          - torch: '2.0.1'   # CUDA 11.7
            py: '3.8'
            variant: 'cu117'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.9'
            variant: 'cu117'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cu117'
            sanitizers: 'nosan'

          - torch: '2.0.1'   # CUDA 11.8
            py: '3.8'
            variant: 'cu118'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.9'
            variant: 'cu118'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cu118'
            sanitizers: 'nosan'

          - torch: '2.0.1'   # ASAN_UBSAN
            py: '3.10'
            variant: 'cpu'
            sanitizers: 'asan_ubsan'
    with:
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      arch: 'x86_64'
      variant: ${{ matrix.variant }}
      sanitizers: ${{ matrix.sanitizers }}

  publish_linux-x86_64:
    name: Publish wheel (pt${{ matrix.torch }}, py${{ matrix.py }}, linux_${{ matrix.arch }}, ${{ matrix.variant }})
    needs: [build_doc, build_wheel-linux-x86_64]
    strategy:
      max-parallel: 1
      matrix:
        include:
          # PT 1.12.1
          - torch: '1.12.1'  # CPU
            py: '3.8'
            variant: 'cpu'
          - torch: '1.12.1'
            py: '3.9'
            variant: 'cpu'
          - torch: '1.12.1'
            py: '3.10'
            variant: 'cpu'

          - torch: '1.12.1'  # CUDA 11.6
            py: '3.8'
            variant: 'cu116'
          - torch: '1.12.1'
            py: '3.9'
            variant: 'cu116'
          - torch: '1.12.1'
            py: '3.10'
            variant: 'cu116'

          # PT 1.13.1
          - torch: '1.13.1'  # CPU
            py: '3.8'
            variant: 'cpu'
          - torch: '1.13.1'
            py: '3.9'
            variant: 'cpu'
          - torch: '1.13.1'
            py: '3.10'
            variant: 'cpu'

          - torch: '1.13.1'  # CUDA 11.6
            py: '3.8'
            variant: 'cu116'
          - torch: '1.13.1'
            py: '3.9'
            variant: 'cu116'
          - torch: '1.13.1'
            py: '3.10'
            variant: 'cu116'

          # PT 2.0.1
          - torch: '2.0.1'   # CPU
            py: '3.8'
            variant: 'cpu'
          - torch: '2.0.1'
            py: '3.9'
            variant: 'cpu'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cpu'

          - torch: '2.0.1'   # CUDA 11.7
            py: '3.8'
            variant: 'cu117'
          - torch: '2.0.1'
            py: '3.9'
            variant: 'cu117'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cu117'

          - torch: '2.0.1'   # CUDA 11.8
            py: '3.8'
            variant: 'cu118'
            sanitizers: 'nosan'
          - torch: '2.0.1'
            py: '3.9'
            variant: 'cu118'
          - torch: '2.0.1'
            py: '3.10'
            variant: 'cu118'
    uses: ./.github/workflows/publish_wheel.yaml
    with:
      os: 'linux'
      torch: ${{ matrix.torch }}
      py: ${{ matrix.py }}
      arch: 'x86_64'
      variant: ${{ matrix.variant }}
      release_type: ${{ inputs.release_type || 'nightly' }}

  publish_doc:
    name: Publish documentation
    needs: [build_doc, build_wheel-linux-x86_64]
    uses: ./.github/workflows/publish_doc.yaml
    with:
      nightly: ${{ github.event_name == 'schedule' || inputs.release_type == 'nightly' }}
